on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        env:
          PGDATABASE: ci_test_db
          PGUSER: postgres
          PGPASSWORD: password
          PGHOST: localhost
        run: |
          npm run test

      - name: Deploy to Render
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "$deploy_url")
          echo "Deploy hook response: $response"
          if [ "$response" -ne 200 ]; then
            echo "Deploy failed"
            exit 1
          fi
